### PR TITLE
Fix gulp watch stopping on error.

### LINKED ISSUE #90: Stops writing CSS after first error in SASS
First, I've reported this issue under floatdrop/gulp-watch#86 thinking it was related to `gulp-watch`, but then I've realized that the issue is gone when I replace `gulp-sass` with `gulp-less`, so I thought maybe this is a `gulp-sass` related issue after all. 

**TL;DR:** `gulp-sass()`stops piping files to destination after a SASS error occurs. Need to restart gulp for the problem to go away.

**Detail:**

1. When SASS files are error free, I see 'Writing sass' message each time I update a `*.scss` file. 
1. Then, I deliberately introduce an error into one of the SASS files. I see an error message from `gulp-plumber` as I should. 
1. However, when I undo this error, I no longer see "Writing sass" message and no CSS files are being written to the `.build/` directory. I need to restart `gulp watch-sass` task to make things go back to normal. 

```coffeescript
# In gulpfile.coffee
sass = require("gulp-sass")
... ... ...
gulp.task "watch-sass", ->
  watch
    glob: filePath.appDir + "/**/*.scss"
  .pipe plumber()
  .pipe sass() # the problem goes away if I replace `sass` with `less`
  .pipe using prefix: "Writing sass" 
  .pipe gulp.dest('.build/')
  return  
```

### PR DESCRIPTION
**Pull request by mariusc23**
Fixes #90. Related to: https://github.com/gulpjs/gulp/issues/259

I think recommending people to not `return` the gulp stream is not a good idea, because gulp will not know when the task is complete, therefore any tasks that depend on sass being done will not be guaranteed that (think race conditions).

### CODE REVIEW

**Comment by Keats** [comment]
Wouldn't it be more consistent with the other plugins I've seen to use gutil.PluginError instead of log ? It should take care of that

**Comment by mariusc23** [comment]
That's a good point. I haven't been using gulp that long so I forgot about gutil. I updated the pull request. Let me know what you think.

File: index.js [hunk 1]
```diff
@@ -148,7 +148,9 @@ gulpSass.sync = function sync(options) {
 // Log errors nicely
 //////////////////////////////
 gulpSass.logError = function logError(error) {
-  gutil.log(gutil.colors.red('[' + PLUGIN_NAME + '] ') + error.messageFormatted);
+  var message = new gutil.PluginError('sass', error.messageFormatted).toString();
+  process.stderr.write(message + '\n');
+  this.emit('end');
```
Comment (Keats) [inline index.js]: i think you can just return a new gutil.PluginError looking at other gulp plugins using cb like  https://github.com/wearefractal/gulp-coffee/blob/master/index.js#L38

**Comment by Snugug** [comment]
@Keats Just tested, `this.emit('end')` is needed.

**Comment by ne0-cz** [comment]
This breaks my gulp setup - I'm not sure if I should open new issue, continue with discussion here or if I'm just using gulp-sass the wrong way.

The stopping of watch on error was a big issue for me, so I found a workaround:
```
.pipe(sass().on('error', function(err) {
    sass.logError(err);
    this.emit('end');
}))
```
This permitted me to have visual bell in console (```console.log('\u0007');```) on error which also greatly helps my current workflow.

My approach is broken by this commit, since ```this.emit('end');``` in ```gulpSass.logError``` function has different ```this``` context depending on the way it's called (my way is not working, the usual ``` .pipe(sass().on('error', sass.logError))``` works).

I don't really understand javascript that much but since this line is the only usage of magic keyword ```this``` in the plugin I feel like this is not way to go - but then again I can't think of any better way since I'm new to the whole gulp/npm scene.

**Comment by jskrzypek** [comment]
@ne0-cz not sure if you managed to get it working in the end, but the issue in your case is that the anonymous function you pass is not bound with the `this` that is used by the parent context. If you want to use it in your previous way you should do this:

```js
.pipe(sass().on('error', function(err) {
    sass.logError(err);
    this.emit('end');
}.bind(this)))
```

Of course with the change I'm not sure it's necessary to call the `this.emit('end')` yourself since `sass.logError()` is now calling it.
